// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "web_wifi_config.h"

static bool s_sta_connected = false;

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    
    lv_display_text(-4, -74, LV_ALIGN_CENTER, "正在启动1，请稍候。。。");
    vTaskDelay(10/portTICK_PERIOD_MS);
    app_wifi_main(&s_sta_connected);
}
