// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "../ui.h"

void ui_Splash_screen_init(void)
{
    ui_Splash = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Splash, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Splash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SysState = ui_Small_Label_create(ui_Splash);
    lv_obj_set_x(ui_SysState, 0);
    lv_obj_set_y(ui_SysState, 75);
    lv_obj_set_align(ui_SysState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SysState, "Init Network...");
    lv_obj_set_style_text_color(ui_SysState, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SysState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LogoLabel = ui_Small_Label_create(ui_Splash);
    lv_obj_set_x(ui_LogoLabel, 0);
    lv_obj_set_y(ui_LogoLabel, 50);
    lv_obj_set_align(ui_LogoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LogoLabel, "Smart Display For CL");
    lv_obj_set_style_text_color(ui_LogoLabel, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LogoLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SysLogo = lv_img_create(ui_Splash);
    lv_img_set_src(ui_SysLogo, &ui_img_sls_logo_png);
    lv_obj_set_width(ui_SysLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SysLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SysLogo, 0);
    lv_obj_set_y(ui_SysLogo, -50);
    lv_obj_set_align(ui_SysLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SysLogo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SysLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Splash, ui_event_Splash, LV_EVENT_ALL, NULL);

}
