// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef _SMART_GADGET_UI_H
#define _SMART_GADGET_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void upanim_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
void ui_event_Splash(lv_event_t * e);
extern lv_obj_t * ui_Splash;
extern lv_obj_t * ui_SysState;
extern lv_obj_t * ui_LogoLabel;
extern lv_obj_t * ui_SysLogo;
// SCREEN: ui_Clock
void ui_Clock_screen_init(void);
void ui_event_Clock(lv_event_t * e);
extern lv_obj_t * ui_Clock;
extern lv_obj_t * ui_Clock_Panel;
extern lv_obj_t * ui_Dot1;
extern lv_obj_t * ui_Dot2;
extern lv_obj_t * ui_Dot3;
extern lv_obj_t * ui_Dot4;
extern lv_obj_t * ui_Dot5;
extern lv_obj_t * ui_Dot6;
extern lv_obj_t * ui_Dot7;
extern lv_obj_t * ui_Dot8;
extern lv_obj_t * ui_Clock_Number1;
extern lv_obj_t * ui_Clock_Number2;
extern lv_obj_t * ui_Clock_Number3;
extern lv_obj_t * ui_Clock_Number4;
extern lv_obj_t * ui_Min;
extern lv_obj_t * ui_Hour;
extern lv_obj_t * ui_Sec;
extern lv_obj_t * ui_Clock_Center;
// SCREEN: ui_Call
void ui_Call_screen_init(void);
void ui_event_Call(lv_event_t * e);
extern lv_obj_t * ui_Call;
extern lv_obj_t * ui_Elena;
extern lv_obj_t * ui_Incoming;
extern lv_obj_t * ui_Call_Incon1;
extern lv_obj_t * ui_Phone1;
extern lv_obj_t * ui_Call_Incon2;
extern lv_obj_t * ui_Phone2;
// SCREEN: ui_Chat
void ui_Chat_screen_init(void);
void ui_event_Chat(lv_event_t * e);
extern lv_obj_t * ui_Chat;
extern lv_obj_t * ui_Chat_container;
extern lv_obj_t * ui_Chat_date;
extern lv_obj_t * ui_C1;
extern lv_obj_t * ui_Chat_Panel1;
extern lv_obj_t * ui_Chat1;
extern lv_obj_t * ui_Chat_Icon1;
extern lv_obj_t * ui_C2;
extern lv_obj_t * ui_Chat_Panel2;
extern lv_obj_t * ui_Chat2;
extern lv_obj_t * ui_Chat_Icon2;
extern lv_obj_t * ui_Delifered;
extern lv_obj_t * ui_C3;
extern lv_obj_t * ui_Chat_Panel3;
extern lv_obj_t * ui_Chat3;
extern lv_obj_t * ui_Chat_Icon3;
// SCREEN: ui_Music_Player
void ui_Music_Player_screen_init(void);
void ui_event_Music_Player(lv_event_t * e);
extern lv_obj_t * ui_Music_Player;
extern lv_obj_t * ui_Music_Title;
extern lv_obj_t * ui_Author;
extern lv_obj_t * ui_Play_btn;
extern lv_obj_t * ui_Play;
extern lv_obj_t * ui_Album;
extern lv_obj_t * ui_Backward;
extern lv_obj_t * ui_Forward;
// SCREEN: ui_Weather
void ui_Weather_screen_init(void);
void ui_event_Weather(lv_event_t * e);
extern lv_obj_t * ui_Weather;
extern lv_obj_t * ui_New_York;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Celsius;
extern lv_obj_t * ui_Weather_Icons;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_W1_Num;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_W2_Num;
extern lv_obj_t * ui_W3_Num;
extern lv_obj_t * ui_W3_Num1;
extern lv_obj_t * ui_W3_Num2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_split;
extern lv_obj_t * ui_yearsplit;
extern lv_obj_t * ui_year;
extern lv_obj_t * ui_split1;
extern lv_obj_t * ui_sec;
extern lv_obj_t * ui_month;
extern lv_obj_t * ui_day;
extern lv_obj_t * ui_yearsplit1;
extern lv_obj_t * ui_min;
// SCREEN: ui_Alarm
void ui_Alarm_screen_init(void);
void ui_event_Alarm(lv_event_t * e);
extern lv_obj_t * ui_Alarm;
extern lv_obj_t * ui_Alarm_container;
extern lv_obj_t * ui_Set_alarm;
extern lv_obj_t * ui_Alarm_Comp;
extern lv_obj_t * ui_Alarm_Comp1;
extern lv_obj_t * ui_Alarm_Comp2;
extern lv_obj_t * ui_Alarm_Comp3;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_sls_logo_png);    // assets/sls_logo.png
LV_IMG_DECLARE(ui_img_pattern_png);    // assets/pattern.png
LV_IMG_DECLARE(ui_img_clock_min_png);    // assets/clock_min.png
LV_IMG_DECLARE(ui_img_clock_hour_png);    // assets/clock_hour.png
LV_IMG_DECLARE(ui_img_clock_sec_png);    // assets/clock_sec.png
LV_IMG_DECLARE(ui_img_phone_png);    // assets/phone.png
LV_IMG_DECLARE(ui_img_chatbox_png);    // assets/chatbox.png
LV_IMG_DECLARE(ui_img_chatbox2_png);    // assets/chatbox2.png
LV_IMG_DECLARE(ui_img_play_png);    // assets/play.png
LV_IMG_DECLARE(ui_img_album_png);    // assets/album.png
LV_IMG_DECLARE(ui_img_backward_png);    // assets/backward.png
LV_IMG_DECLARE(ui_img_forward_png);    // assets/forward.png
LV_IMG_DECLARE(ui_img_cloud_png);    // assets/cloud.png
LV_IMG_DECLARE(ui_img_weather_1_png);    // assets/weather_1.png
LV_IMG_DECLARE(ui_img_weather_2_png);    // assets/weather_2.png
LV_IMG_DECLARE(ui_img_weather_3_png);    // assets/weather_3.png
LV_IMG_DECLARE(ui_img_pattern_png);    // assets/pattern.png
LV_IMG_DECLARE(ui_img_tq_03duoyun_png);    // assets/tq_03duoyun.png
LV_IMG_DECLARE(ui_img_556198778);    // assets/湿的.png
LV_IMG_DECLARE(ui_img_277457461);    // assets/风(1).png
LV_IMG_DECLARE(ui_img_745566655);    // assets/大气湿度.png
LV_IMG_DECLARE(ui_img_845915064);    // assets/低温.png
LV_IMG_DECLARE(ui_img_341460266);    // assets/高温.png
LV_FONT_DECLARE(ui_font_Number);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
