// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "esp_log.h"
#include "ui_display_handler.h"

void lv_display_init(void){

}

void lv_display_text(font_display_t font){
    LV_FONT_DECLARE(siyuan_simple_20);
    lv_obj_set_width(font.label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(font.label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(font.label, font.x);
    lv_obj_set_y(font.label, font.y);
    if(font.mode != NULL){
        lv_obj_set_width(font.label, 250);
        lv_label_set_long_mode(font.label, font.mode);
        lv_obj_set_style_anim_speed(font.label, 5,_LV_STYLE_STATE_CMP_SAME);
    }
    
    if(font.alignments == NULL){
        lv_obj_set_align(font.label, LV_ALIGN_CENTER);
    } else {
        lv_obj_set_align(font.label, font.alignments);
    }
    
    lv_obj_set_style_text_font(font.label, &siyuan_simple_20,0);
    lv_label_set_text(font.label, font.text);
}


void lv_flush_full_screen(void){
    lv_refr_now(NULL);
}

font_display_t set_display_font(lv_obj_t *label,int x, int y,lv_label_long_mode_t mode, lv_align_t alignments, char *text){
    font_display_t font_display_instance;
    font_display_instance.label = label;
    font_display_instance.x = x;
    font_display_instance.y = y;
    font_display_instance.mode = mode;
    font_display_instance.alignments = alignments;
    font_display_instance.text = text;
    return font_display_instance;
}

void lv_display_spinner(int x, int y, int width, int height,lv_obj_flag_t flag)
{
    // if(ui_Spinner1 == NULL){
    //     ui_Spinner1 = lv_spinner_create(ui_Screen1, 10000, 90);
    // }
    // lv_obj_set_width(ui_Spinner1, width);
    // lv_obj_set_height(ui_Spinner1, height);
    // lv_obj_set_x(ui_Spinner1, x);
    // lv_obj_set_y(ui_Spinner1, y);
    // lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    // if(LV_OBJ_FLAG_HIDDEN == flag){
    //     lv_obj_add_flag(ui_Spinner1,flag);
    //     lv_flush_full_screen();
    // } else if (LV_OBJ_FLAG_CLICKABLE == flag){
    //     lv_obj_clear_flag(ui_Spinner1, flag);      /// Flags
    // }
}
