// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_DISPLAY_HANDLER_H
#define _SQUARELINE_PROJECT_UI_DISPLAY_HANDLER_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void lv_display_text(int x, int y, lv_align_t alignments,char *text);
void lv_display_spinner(int x, int y, lv_align_t alignments, char *text);
void lv_display_init(void);
void lv_deisplay_text_update(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
