// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

void lv_display_init(void){

}

void lv_display_text(int x, int y, lv_align_t alignments, char *text)
{
    LV_FONT_DECLARE(siyuan_simple_20);
    if(ui_Label1 == NULL){
        ui_Label1 = lv_label_create(ui_Screen1);
    }
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, x);
    lv_obj_set_y(ui_Label1, y);
    lv_obj_set_align(ui_Label1, alignments);
    lv_obj_set_style_text_font(ui_Label1, &siyuan_simple_20,0);
    lv_label_set_text(ui_Label1, text);
}

void lv_display_spinner(int x, int y, int width, int height)
{
    ui_Spinner1 = lv_spinner_create(ui_Screen1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, width);
    lv_obj_set_height(ui_Spinner1, height);
    lv_obj_set_x(ui_Spinner1, x);
    lv_obj_set_y(ui_Spinner1, y);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
}
